### ISSUE TITLE
proliphix.py line 93: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by chefdeit** [sdague/proliphix#8]
Hi, in current and recent HomeAssistant, getting:

```
Error while setting up proliphix platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/proliphix/climate.py", line 52, in setup_platform
    pdp.update()
  File "/usr/local/lib/python3.10/site-packages/proliphix/proliphix.py", line 93, in update
    oid, value = line.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
```

This possibly causes downstream HA entity warning:

> This entity ('climate.livingrmtstat') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.

Perhaps it might be possible for the integration to generate the MAC based unique ID per https://developers.home-assistant.io/docs/entity_registry_index/ ?

Many thanks!

**Comment by chefdeit** [comment]
P.S. the thermostat shows up in HA dashboard and the temperature control does work but can't assign it to an area and the Mode pull-down is empty / other issues possibly related to entity being read-only due to no unique ID
